DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS recipe;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE recipe (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  desc TEXT NOT NULL,
  type TEXT NOT NULL,
  cook_time TEXT NOT NULL,
  nutrition TEXT NOT NULL
  -- FOREIGN KEY (author_id) REFERENCES user (id)
);
